language: node_js
node_js:
- '6'
- '10'
script:
- yarn lint
- yarn test
- yarn build
cache: yarn
deploy:
  provider: npm
  skip_cleanup: true
  email: domoritz@gmail.com
  api_key:
    secure: ONaZNIbNJSXk9QJ/Nardk85lSGAwCe/WIdgagGFlW1utygCgByQ6awgD3JPw58mF1AUfGEWnwczqKe84D6vbiVxcrlf7vqs3S3OPLX2lhkWmik2H6SRrnrhN7Z/84ng7vveFz1TVpyxKAIuCNikek0elrPoRoYBXDqtZRX0ozfOIMUsSiqXUmt3IDNaNyJRhS4NW8344VVfonUMTz81tpQGaHt7nC6MJ8GyMYrnRVNNdgpJu3wBDPPKgkuw9GIYLiluUQZ8CEU3TSQwZqDeAegF4qPVfbwAFBZcUzdDjCKLHa/f4cEgs2xJiaQ+HMF6ESgzb8PnGQ5sbT19XER4NOCGDTssdPIwOlq5GZ2npsR1AhG72kIWgfuk60cv2dtJup0AQ3qBsj3RY4SCUtydraQjlKUc06EueW8E280LZcLm5AWZZtpQJY6KDVdlYfX2meFJjMz0sMOq+kjLvzF/67KTShjNtl14SSexnUjriF/uLKTO9ulpZM/r93X+4NGQtx/w8V1mwlUcRGZXwTQoub6H/Gb5d2X/RGTVw0L6MyAhhN3WXLwiSnCFvDV5D0gwN/Yy8Q3QTYlTa/JaekKfqLrJJEMbONo1AO2PCapjjwznzJjCcHix3nWVNMzfBUOqB8SfHuzb58+SBCxeQkWJfIzxKbNCKlU9eVzFMWxeqqGE=
  on:
    tags: true
    repo: vega/ts-json-schema-generator
    node: '10'
